apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-psql-demo-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: spring-boot-psql-demo
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: spring-boot-psql-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: spring-boot-psql-demo
    spec:
      containers:
        - name: postgres
          image: "postgres:9.6"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "info_db"
          ports:
            - name: psql
              containerPort: 5432
              protocol: TCP
          resources:
            {}