apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-psql-demo
  labels:
    app.kubernetes.io/instance: "spring-boot-psql-demo"
    app.kubernetes.io/version: "1.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-psql-demo
      app.kubernetes.io/instance: spring-boot-psql-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-boot-psql-demo
        app.kubernetes.io/instance: spring-boot-psql-demo
    spec:
      containers:
        - name: spring-boot-psql-demo
          image: "parthpatil3110/spring-boot-psql-demo:0.1.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: PG_HOST
              value: "spring-boot-psql-demo-postgres"
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: "info_db"
            - name: PG_USER
              value: "admin"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}