apiVersion: v1
kind: Service
metadata:
  name: spring-boot-psql-demo
  labels:
    app.kubernetes.io/instance: "spring-boot-psql-demo"
    app.kubernetes.io/version: "1.0"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: spring-boot-psql-demo
    app.kubernetes.io/instance: spring-boot-psql-demo