apiVersion: v1
kind: Service
metadata:
  name: spring-boot-psql-demo-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: spring-boot-psql-demo
    app.kubernetes.io/version: "1.0"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: spring-boot-psql-demo